services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: addr_php
    volumes:
      - ./:/var/www/html:cached
    working_dir: /var/www/html
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - addrnet

  nginx:
    image: nginx:1.25-alpine
    container_name: addr_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - addrnet

  db:
    image: postgres:15
    container_name: addr_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    networks:
      - addrnet

  node:
    image: node:20
    container_name: addr_node
    working_dir: /src
    volumes:
      - ./frontend:/src
      - ./public/assets:/src/../public/assets
    command: ["sh", "-c", "npm install && npm ci && npm run build:all"]
    networks:
      - addrnet

volumes:
  pgdata:

networks:
  addrnet:
